### PR TITLE
EricM5 - Fix Bug 'Search by Instructor's '+' button in table does nothing'

### LINKED ISSUE #2: BUG: Search by Instructor's '+' button in table does nothing
### Summary

While performing any search, courses in the results table that contain sections will be distinguished by a '+' button on the left side of the row. Clicking the button will reveal the section times for that course.
If you perform a Search by Instructor, the same + buttons will appear for courses that have section times. Clicking this drop down results in nothing happening. 
My guess is that the reason nothing happens is while performing a search by instructor, only courses and sections with the searched for name show up in the table. So even though a course appears with a + button, no sections appear because the section TA's almost always have a different name from the professor.

### Expected Behavior

There are two potential solutions to this.

1. Remove the + sign from all "Search by Instructor" searches.

2. Have sections show up in the drop down despite not having the same name as the instructor search.

### Current / Observed Behavior

If you perform a Search by Instructor, the same + buttons will appear for courses that have section times. Clicking this drop down results in nothing happening. 

### Steps to Reproduce

1. Go to Search by Instructor
2. Set start quarter to W20 and end quarter to S23
3. Set instructor search to "Conrad"
4. Click drop down buttons for the resulting rows.

See here that the first two drop downs result in nothing, while the third drop down works successfully.
image

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by EricM5**
Fixed bug.

When on Search By Instructor page, I pass in a new attribute (to a prop) to tell the table which page that is sending the form. If the page field == 'CourseOverTimeInstructor', then the table will omit the options to display the '+' and '-', eliminating the dropdown option.

After Edit:

image

closes #2

### CODE REVIEW

**Review by apzhou0 — APPROVED** [review]
LGTM

File: frontend/src/main/components/Sections/SectionsTable.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ function getFirstVal(values) {
   return values[0];
 }
 
-export default function SectionsTable({ sections }) {
+export default function SectionsTable(props) {
```
Comment (chriscerie) [inline frontend/src/main/components/Sections/SectionsTable.js:17]: Why change this? Destructuring props is much more readable because you can immediately see what props the component accepts. Without it, you’d need to look at the component definition.

File: frontend/src/main/components/SectionsTableBase.js [hunk 2]
```diff
@@ -7,6 +7,7 @@ export default function SectionsTableBase({
   columns,
   data,
   testid = "testid",
+  page,
```
Comment (chriscerie) [inline frontend/src/main/components/SectionsTableBase.js:10]: It’s not immediately clear to readers what `page` actually does. Initially I thought you were adding pagination to the table. A more idiomatic approach to this would be along the lines of a `canExpand` prop.

Also, this approach omits expand for all rows, even for rows that have the same instructor teaching the section. Is that actually what you want? Perhaps a less brittle approach is to investigate why the existing check for `row.subRows.length` is not working as intended.

File: frontend/src/main/components/Sections/SectionsTable.js (hunk 1 above)
Comment (pconrad) [inline frontend/src/main/components/Sections/SectionsTable.js:17]:
```suggestion
export default function SectionsTable({sections, canExpand=true}) {
```

If, instead, we make this a prop that describes the functionality and has a default value of the old behavior, then it will be backwards compatible with existing components, and easy to use the alternative behavior in future components.

File: frontend/src/tests/components/SectionsTableBase.test.js [hunk 3]
```diff
@@ -149,4 +149,17 @@ describe("SectionsTableBase tests", () => {
...
     );
   });
+
+  test("when on Instructor Search Page, No +/- is displayed for dropdown", () => {
+    render(
+      <SectionsTableBase
+        columns={columns}
+        data={fiveSections}
+        group={false}
+        page="CourseOverTimeInstructor"
```
Comment (pconrad) [inline frontend/src/tests/components/SectionsTableBase.test.js:159]:
```suggestion
        canExpand={false}
```

**Review by pconrad — CHANGES_REQUESTED** [review]
I have a few suggestions that are in alignment with @chriscerie 's suggesitons

**Review by apzhou0 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!
