### PR TITLE
azhou - Personal Schedule Default Quarter Fix

### LINKED ISSUE #11: BUG: Creating personal schedule fails first try until quarter field changed
### Summary

Creating personal schedule fails on the first attempt until quarter field is changed.
It gives a toast: "Error: undefined"

### Expected Behavior

Creation works even with default selected quarter.

### Current / Observed Behavior

See above

### Steps to Reproduce

See above

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by apzhou0**
In this PR, we fix the issue of personal schedule creation failing before the quarter field is changed. 

Dokku Link: https://proj-courses-apzhou0-dev.dokku-12.cs.ucsb.edu/

To test, click on the link above and log in. Click on "Personal Schedules," select "Add Schedule," and enter a name and description but click "create" without changing the quarter. No errors should appear. Also try the same thing using incognito mode, as this should reset localStorage. 
 
Closes #11

### CODE REVIEW

**Review by alicezhong1 — APPROVED** [review]
LGTM, clear instructions and works on the dokku link

File: frontend/src/main/components/Quarters/SingleQuarterDropdown.js [hunk 1]
```diff
@@ -20,6 +20,9 @@ function SingleQuarterDropdown({
   onChange = null,
   label = "Quarter",
 }) {
+  if (!localStorage.getItem(controlId)) {
+    localStorage.setItem(controlId, quarters[0].yyyyq);
+  }
```
Comment (chriscerie) [inline frontend/src/main/components/Quarters/SingleQuarterDropdown.js:25]: React components must be pure as a rule and cannot have side effects during render. I would instead investigate why the fallback value in the useState is not working as intended. My suspicion is that the useState there isn't needed at all since the parent component is passing the same data down, and splitting source of truth like that is what causes these types of out of sync bugs.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js#L42

Comment (apzhou0) [reply frontend/src/main/components/Quarters/SingleQuarterDropdown.js:25]: https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L39

Am I supposed to change this line so that it doesn't take the quarter from localStorage? I looked through the other files and did not see any place where the quarter value in localStorage is set to some default value, so I assumed that I would have to do that in SingleQuarterDropdown.js

Comment (chriscerie) [reply frontend/src/main/components/Quarters/SingleQuarterDropdown.js:25]: In this case this state gets initialized with a fallback value, but localstorage falls behind.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L28-L31

The bug is the form reads the localstorage value (which is behind) over the react state. localstorage never syncs with the react state until the field is changed.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L35

This just goes to show the danger of splitting source of truth into duplicate states. The easiest way fix the issue is to implement the same fallback logic in the send function
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L39

...but there's still an issue of duplicate state which harms readability. A better (but more involved) approach is to
* define the selected quarter state in the `PersonalSchedulesCreatePage`
* sync localstorage with it with `useEffect`
* change the onSubmit to read from the react state
* pass the created state and its setter down to `SingleQuarterDropdown` and remove these two unnecessary states
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js#L31-L35
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L28-L31
* ensure the new state in gets updated by `SingleQuarterDropdown`, so this except reference the new state setter
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L36

Either approach is fine. The 1st one will be easy but won't fix the root of the issue.

Comment (apzhou0) [reply frontend/src/main/components/Quarters/SingleQuarterDropdown.js:25]: Thank you!

**Review by EricM5 — APPROVED** [review]

**Comment by pconrad** [comment]
So, the dokku deployment still seems to have the bug for me:

code-review

**Review by pconrad — CHANGES_REQUESTED** [review]
For me, it doesn't seem to have fixed the bug.

@chriscerie also makes some good suggestions about implementation. You may want to create a separate branch and try his approach. If it fixes the problem you can make a separate PR and close this one.

In any case, whether this approach, or the alternative, we need something that actually fixes the bug.

**Comment by chriscerie** [comment]
Please, still address the review in https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/26#discussion_r1401336976. It might technically work now, but it still breaks react’s purity rule. Best case scenario it sets a bad precedent, worst case it causes a bug that will be very* difficult to find the root cause.

**Review by pconrad — APPROVED** [review]
LGTM
